channels:
- conda-forge
dependencies:
- pyiron =0.4.7
- pyiron_atomistics =0.2.62
- pyiron-data =0.0.20
- nglview =3.0.3
- lammps =2022.06.23=*openmpi*
- openkim-models =2021.01.28
- sqlalchemy <2.0.0
