channels:
- conda-forge
- conda-forge/label/broken
dependencies:
- python =3.8*
- lammps =2021.08.31=*mpich*
- damask =3.0.0
- vtk
- itkwidgets
- pyvista
- pymatgen =2022.0.14
- sqsgenerator =0.0.5
- fenics =2019.1.0
- mshr =2019.1.0
- pyiron_continuum =0.0.2
- pyiron_gpl =0.0.3
