channels:
- conda-forge
dependencies:
- damask =3.0.0a8
- fenics =2019.1.0=*_38
- mshr =2019.1.0=*_9
- pyiron_continuum =0.0.6
- pyiron_atomistics =0.3.4
- pyiron_gpl =0.0.3
- pymatgen =2023.11.12
- pyvista =0.42.3
- sqsgenerator =0.3
- vtk =9.2.6
