channels:
- conda-forge
- nodefaults
dependencies:
- aimsgb =1.1.1
- atomicrex =1.0.4
- bader =1.0.5
- calphy =1.3.13
- fitsnap3 =3.1.0.4
- nbgitpuller =1.2.2
- pyiron_contrib =0.1.18
- pyiron_potentialfit =0.3.8
- pyiron_workflow =0.11.2
- pyiron_gui =0.0.12
- pyironflow =0.0.5
- matgl =1.1.2
- mlip =2.0
- sqsgenerator =0.3
- pyiron_gpl =0.0.5
- python-ace =0.3.0
- pytorch =2.1.2
- pyxtal =1.0.6
- runner =1.3
- structdbrest =0.0.1
- tensorflow =2.17.0
- psycopg2 =2.9.9
- numba =0.60.0
- llama-index =0.12.9
- jupyter-server-proxy =4.4.0
- jupyterhub =5.2.1
- flux-core =0.64.0
- netcdf4 =1.7.1
- maxvolpy =0.3.8
- bokeh =3.6.3
