name: Docker Push

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "date=$(date +%F)" >> $GITHUB_OUTPUT
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ steps.date.outputs.date }}
          tag_exists_error: false
          message: ""
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: docker build -t pyiron/base:latest base/
      - run: docker tag pyiron/base:latest pyiron/base:"$(date +%F)"
      - run: docker build -t pyiron/md:latest md/
      - run: docker tag pyiron/md:latest pyiron/md:"$(date +%F)"
      - run: docker build -t pyiron/pyiron:latest pyiron/
      - run: docker tag pyiron/pyiron:latest pyiron/pyiron:"$(date +%F)"
      - run: docker build -t pyiron/potentialworkshop:latest potentialworkshop/
      - run: docker tag pyiron/potentialworkshop:latest pyiron/potentialworkshop:"$(date +%F)"
      - run: docker build -t pyiron/experimental:latest experimental/
      - run: docker tag pyiron/experimental:latest pyiron/experimental:"$(date +%F)"
      - run: docker build -t pyiron/continuum:latest continuum/
      - run: docker tag pyiron/continuum:latest pyiron/continuum:"$(date +%F)"
      - run: docker images
      - run: docker push pyiron/base:latest
      - run: docker push pyiron/base:"$(date +%F)"
      - run: docker push pyiron/md:latest
      - run: docker push pyiron/md:"$(date +%F)"
      - run: docker push pyiron/pyiron:latest
      - run: docker push pyiron/pyiron:"$(date +%F)"
      - run: docker push pyiron/potentialworkshop:latest
      - run: docker push pyiron/potentialworkshop:"$(date +%F)"
      - run: docker push pyiron/experimental:latest
      - run: docker push pyiron/experimental:"$(date +%F)"
      - run: docker push pyiron/continuum:latest
      - run: docker push pyiron/continuum:"$(date +%F)"
      - run: mkdir -p environment; chmod 777 environment
      - run: docker run -v $(pwd)/environment:/home/jovyan/ --rm pyiron/base /bin/bash -c 'source /opt/conda/bin/activate; conda env export > /home/jovyan/pyiron_base_$(date +%F).yml;' 
      - run: docker run -v $(pwd)/environment:/home/jovyan/ --rm pyiron/md /bin/bash -c 'source /opt/conda/bin/activate; conda env export > /home/jovyan/pyiron_md_$(date +%F).yml;' 
      - run: docker run -v $(pwd)/environment:/home/jovyan/ --rm pyiron/continuum /bin/bash -c 'source /opt/conda/bin/activate; conda env export > /home/jovyan/pyiron_continuum_$(date +%F).yml;' 
      - run: docker run -v $(pwd)/environment:/home/jovyan/ --rm pyiron/pyiron /bin/bash -c 'source /opt/conda/bin/activate; conda env export > /home/jovyan/pyiron_pyiron_$(date +%F).yml;' 
      - run: docker run -v $(pwd)/environment:/home/jovyan/ --rm pyiron/potentialworkshop /bin/bash -c 'source /opt/conda/bin/activate; conda env export > /home/jovyan/pyiron_potentialworkshop_$(date +%F).yml;' 
      - run: docker run -v $(pwd)/environment:/home/jovyan/ --rm pyiron/experimental /bin/bash -c 'source /opt/conda/bin/activate; conda env export > /home/jovyan/pyiron_experimental_$(date +%F).yml;'
      - run: ls -al environment
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: environment/pyiron_*.yml
