name: Create tag

on:
  repository_dispatch:
    types: [build]
  schedule:
    - cron: "0 0 * * 1"
  pull_request:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "date=$(date +%F)" >> $GITHUB_OUTPUT
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ steps.date.outputs.date }}
          tag_exists_error: false
          message: ""
